controller:
  name: controller
  ingressClassByName: true
  image:
    registry: registry.eu-central-1.harbor.vodafone.com/gks-public-cloud
    image: ingress-nginx/controller
    tag: "v1.0.2"
    digest: ""
  service:
    externalTrafficPolicy: "Local"
    enabled: true
    annotations: 
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Project_Name=tag_project_name,Managed_By=tag_managed_by,Tagging_Version=tag_tagging_version,Confidentiality=tag_confidentiality,Environment=tag_environment,Security_Zone=tag_security_zone"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp     
    externalIPs: []
    loadBalancerSourceRanges: []
    internal:     
      enabled: true
      annotations: 
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Project_Name=tag_project_name,Managed_By=tag_managed_by,Tagging_Version=tag_tagging_version,Confidentiality=tag_confidentiality,Environment=tag_environment,Security_Zone=tag_security_zone"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp     
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      loadBalancerSourceRanges: []
      externalTrafficPolicy: "Local"
    patch:
      enabled: true
      image:
        registry: registry.eu-central-1.harbor.vodafone.com/gks-public-cloud
        image: ingress-nginx/kube-webhook-certgen
        tag: v1.0
#defaultBackend:
#  enabled: false
#  name: defaultbackend
#  image:
#    registry: registry.eu-central-1.harbor.vodafone.com/gks-public-cloud
#    image: defaultbackend-amd64
#    tag: "1.5"
imagePullSecrets:
  - name: regcred
